# --- main configuration -------------------------------------------
# see http://www.emoji-cheat-sheet.com/

baseurl		 	       : "https://flashpixx.de/"
ignoreFiles            : [ "\\.graffle$", "\\.sh$", "\\.config" ]
metadataformat		   : "yaml"
defaultContentLanguage : "en"     
theme 			       : "flashpixx"
title                  : "flashpixx.de"
enableEmoji            : true
enableRobotsTXT        : true
googleAnalytics		   : "UA-4509379-1"

permalinks:
    projekt            : "/:section/:filename" 

taxonomies:
    projekt            : "projects"


params:
    owner			   : "Philipp Kraus"
    description 	   : "Developing of AI and Big-Data technologies"
    keywords           : "AI, Developing, Big-Data, Machine-Learning"
    date_format        : "2006-01-02"
    bingverify         : "2EB13C5538E9973D8DFC39C6A455DEFE"
    socialmedia 	   :
        -
            name	   : "mail"
            url        : "mailto:philipp.kraus [AT] flashpixx [DOT] de"
            weight	   : 0
        -
            name	   : "github"
            url	       : "https://github.com/flashpixx"
            weight	   : 10            
        -
            name	   : "gitlab"
            url	       : "https://gitlab.com/flashpixx"
            weight	   : 20            
        -
            name	   : "docker"
            url	       : "https://hub.docker.com/u/flashpixx/"
            weight	   : 30
        -
            name	   : "linkedin"
            url 	   : "https://www.linkedin.com/in/philipp-kraus"
            weight	   : 40
        -
            name	   : "xing"
            url        : "https://xing.to/philippkraus"
            weight	   : 50
        -
            name	   : "twitter"
            url		   : "https://twitter.com/flashpixx"
            weight	   : 60
        -
            name	   : "keybase"
            url		   : "https://keybase.io/flashpixx"
            weight	   : 70    
        -
            name	   : "vimeo"
            url		   : "https://vimeo.com/user84670997"
            weight	   : 80    
        -
            name 	   :  "facebook"
            url 	   : "https://www.facebook.com/philipp.kraus"
            weight	   : 90
        -
            name	   : "googleplus"
            url	       : "https://plus.google.com/116548835083550863516"
            weight	   : 100

# ----------------------------------------------------------------------
